import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react';

export default function Home() {
  const [userInput, setUserInput] = useState({});

  function handleUserInput(e){
    e.preventDefault();

    const inputObject = {
      "location":e.target.location.value,
      "minCustomers": e.target.min_cph.value,
      "maxCustomers": e.target.max_cph.value,
      "avgCookies": e.target.avg_cps.value,
    }

    setUserInput(inputObject)
  }

  return (
    <div className="">
      <Head>
        <title>Cookie Stand Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='flex justify-between bg-teal-600  text-gray-50 p-4'>
        <h1 className=" text-2xl text-black font-semibold">
          Cookie Stand Admin
        </h1>
      </header>

      <main className="">
        <div className='bg-teal-300 h-44 mx-20 my-5'>
          <p className='relative text-center font-semibold text-xl mb-3 pt-5'>Create Cookie Stand</p>
          <form onSubmit={handleUserInput} className='mx-auto'>
            <div className='flex my-2 mb-4 '>
              <label htmlFor="" className='ml-5 mr-2 font-semibold'>Location</label>
              <input className='w-11/12 text-black rounded' type="text" name='location' />
            </div>

            <div className='flex'>
              <div className='inline-block ml-5 w-1/4 h-16 bg-green-500'>
                <label htmlFor="" className='font-semibold ml-6'>Minimum Customers per Hour</label>
                <input className='relative w-5/6 ml-6 rounded' type="text" name='min_cph' />
              </div>

              <div className='inline-block ml-5 w-1/4 h-16 bg-green-500'>
                <label htmlFor="" className='font-semibold ml-6'>Maximum Customers per Hour</label>
                <input className='relative w-5/6 ml-6 rounded' type="text" name='max_cph' />
              </div>

              <div className='inline-block ml-5 w-1/4 h-16 bg-green-500'>
                <label htmlFor="" className='font-semibold ml-10'>Average Cookies per Sale</label>
                <input className='relative w-5/6 ml-6 rounded' type="text" name='avg_cps' />
              </div>

              <div className='ml-5 mr-5 w-1/4 h-16 bg-green-500 hover:scale-105 cursor-pointer rounded'>
                <input type="submit" className='w-full h-full font-semibold' value="Create" />
              </div>
              
            </div>

          </form>
        </div>

        <p className='text-center'>Report table coming soon...</p>
        <br />
        <p className='text-center'>{JSON.stringify(userInput)}</p>

      </main>

      <footer className="bg-teal-600  text-black p-4 mt-8 mb-0 ">
        <p>&copy; 2022</p>
      </footer>

    </div>
  )
}
